/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GroupProject;

/**
 *
 * @author dianaevtimova
 */
public class Question extends javax.swing.JFrame {
    
    private static int count = 0;
    private static final int MAX = 10;

    /**
     * Creates new form Question
     */
    public Question() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CodeSide = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        code = new javax.swing.JTextArea();
        AnswerSide = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        question = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        answer = new javax.swing.JTextField();
        submit_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Question");
        setAutoRequestFocus(false);
        setPreferredSize(new java.awt.Dimension(800, 500));
        getContentPane().setLayout(null);

        CodeSide.setBackground(new java.awt.Color(255, 255, 255));
        CodeSide.setMinimumSize(new java.awt.Dimension(400, 500));

        code.setBackground(new java.awt.Color(255, 231, 208));
        code.setColumns(20);
        code.setRows(5);
        jScrollPane1.setViewportView(code);

        javax.swing.GroupLayout CodeSideLayout = new javax.swing.GroupLayout(CodeSide);
        CodeSide.setLayout(CodeSideLayout);
        CodeSideLayout.setHorizontalGroup(
            CodeSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CodeSideLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        CodeSideLayout.setVerticalGroup(
            CodeSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CodeSideLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        getContentPane().add(CodeSide);
        CodeSide.setBounds(0, 0, 400, 500);

        AnswerSide.setBackground(new java.awt.Color(255, 204, 153));
        AnswerSide.setPreferredSize(new java.awt.Dimension(400, 500));

        title.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        title.setForeground(new java.awt.Color(50, 91, 110));
        title.setText("Question");

        question.setFont(new java.awt.Font("Georgia", 0, 22)); // NOI18N
        question.setForeground(new java.awt.Color(50, 91, 110));
        question.setText("What will be the output of the code?");

        type.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        type.setForeground(new java.awt.Color(50, 91, 110));
        type.setText("Type your answer here:");

        answer.setFont(new java.awt.Font("Georgia", 0, 12)); // NOI18N

        submit_button.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        submit_button.setForeground(new java.awt.Color(50, 91, 110));
        submit_button.setText("Sumbit");
        submit_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout AnswerSideLayout = new javax.swing.GroupLayout(AnswerSide);
        AnswerSide.setLayout(AnswerSideLayout);
        AnswerSideLayout.setHorizontalGroup(
            AnswerSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnswerSideLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(type)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(AnswerSideLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(question)
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnswerSideLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(AnswerSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnswerSideLayout.createSequentialGroup()
                        .addComponent(submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(143, 143, 143))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, AnswerSideLayout.createSequentialGroup()
                        .addComponent(title)
                        .addGap(115, 115, 115))))
        );
        AnswerSideLayout.setVerticalGroup(
            AnswerSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AnswerSideLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(question, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(AnswerSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(answer, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(type))
                .addGap(37, 37, 37)
                .addComponent(submit_button, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147))
        );

        getContentPane().add(AnswerSide);
        AnswerSide.setBounds(400, 0, 408, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submit_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit_buttonActionPerformed
        while (count <= MAX) {
        Question QuestionFrame = new Question();
        QuestionFrame.setVisible(true);
        QuestionFrame.pack();
         
        //Let the frame be displayed in the center
        QuestionFrame.setLocationRelativeTo(null);
        count++;
        this.dispose();
        }
        
        if(count > MAX){
            Result ResultFrame = new Result();
            ResultFrame.setVisible(true);
            ResultFrame.pack();
            
            ResultFrame.setLocationRelativeTo(null);
            this.dispose();
        }
    }//GEN-LAST:event_submit_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Question.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Question().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AnswerSide;
    private javax.swing.JPanel CodeSide;
    private javax.swing.JTextField answer;
    private javax.swing.JTextArea code;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel question;
    private javax.swing.JButton submit_button;
    private javax.swing.JLabel title;
    private javax.swing.JLabel type;
    // End of variables declaration//GEN-END:variables
}
