/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GroupProject;

/**
 *
 * @author dianaevtimova
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    public SignUp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LogoSide = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        DataSide = new javax.swing.JPanel();
        titel = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        name_input = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        username_input = new javax.swing.JTextField();
        password_input = new javax.swing.JPasswordField();
        account = new javax.swing.JLabel();
        signup_button = new javax.swing.JButton();
        login_button = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sign Up");
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setLayout(null);

        LogoSide.setBackground(new java.awt.Color(255, 255, 255));
        LogoSide.setPreferredSize(new java.awt.Dimension(400, 500));

        jLabel1.setIcon(new javax.swing.ImageIcon("/Users/dianaevtimova/Desktop/GroupProject/src/Java_Icon/pngegg (1).png")); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(400, 500));

        javax.swing.GroupLayout LogoSideLayout = new javax.swing.GroupLayout(LogoSide);
        LogoSide.setLayout(LogoSideLayout);
        LogoSideLayout.setHorizontalGroup(
            LogoSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoSideLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogoSideLayout.setVerticalGroup(
            LogoSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoSideLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        jPanel1.add(LogoSide);
        LogoSide.setBounds(0, 0, 400, 500);

        DataSide.setBackground(new java.awt.Color(255, 204, 153));
        DataSide.setPreferredSize(new java.awt.Dimension(400, 500));

        titel.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        titel.setForeground(new java.awt.Color(50, 91, 110));
        titel.setText("SIGN UP");

        name.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        name.setForeground(new java.awt.Color(50, 91, 110));
        name.setText("Full Name:");

        username.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(50, 91, 110));
        username.setText("Username:");

        password.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        password.setForeground(new java.awt.Color(50, 91, 110));
        password.setText("Password:");

        password_input.setToolTipText("");

        account.setFont(new java.awt.Font("Georgia", 2, 16)); // NOI18N
        account.setText("You already have an account?");

        signup_button.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        signup_button.setForeground(new java.awt.Color(50, 91, 110));
        signup_button.setText("Sign Up");
        signup_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_buttonActionPerformed(evt);
            }
        });

        login_button.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        login_button.setForeground(new java.awt.Color(50, 91, 110));
        login_button.setText("Login");
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataSideLayout = new javax.swing.GroupLayout(DataSide);
        DataSide.setLayout(DataSideLayout);
        DataSideLayout.setHorizontalGroup(
            DataSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataSideLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(DataSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataSideLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(account)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))
                    .addGroup(DataSideLayout.createSequentialGroup()
                        .addGroup(DataSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(name)
                            .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(DataSideLayout.createSequentialGroup()
                        .addGroup(DataSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(password)
                            .addComponent(username))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(DataSideLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(titel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        DataSideLayout.setVerticalGroup(
            DataSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataSideLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(name_input, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(username)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(username_input, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(password)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(password_input, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(signup_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(DataSideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(account)
                    .addComponent(login_button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        name_input.getAccessibleContext().setAccessibleName("");

        jPanel1.add(DataSide);
        DataSide.setBounds(400, 0, 400, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 155, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
        Login LoginFrame = new Login();
        LoginFrame.setVisible(true);
        LoginFrame.pack();
         
        //Let the frame be displayed in the center
        LoginFrame.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_login_buttonActionPerformed

    private void signup_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_buttonActionPerformed
        // TODO add your handling code here:
        Difficulty DifficultyFrame = new Difficulty();
        DifficultyFrame.setVisible(true);
        DifficultyFrame.pack();
         
        //Let the frame be displayed in the center
        DifficultyFrame.setLocationRelativeTo(null);
        
        this.dispose();
    }//GEN-LAST:event_signup_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DataSide;
    private javax.swing.JPanel LogoSide;
    private javax.swing.JLabel account;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton login_button;
    private javax.swing.JLabel name;
    private javax.swing.JTextField name_input;
    private javax.swing.JLabel password;
    private javax.swing.JPasswordField password_input;
    private javax.swing.JButton signup_button;
    private javax.swing.JLabel titel;
    private javax.swing.JLabel username;
    private javax.swing.JTextField username_input;
    // End of variables declaration//GEN-END:variables
}
